theme: jekyll-theme-cayman
url: "https://efficientaiworkshop.github.io"
baseurl: ""
title: "1st Data and Model Efficiency for Scalable AI Workshop"
title_html: "1st Data and Model Efficiency<br>for Scalable AI Workshop"
description: "IEEE BigData 2026 Workshop &middot; Phoenix, AZ, USA"
subtitle: "December 14&ndash;17, 2026 &middot; Precise time and date TBD"
show_downloads: false
